---

- name: create fabric-ca gui cronjob
  template:
    src: "{{ cagui_cronjob_template }}"
    dest: "{{ cagui_cronjob_path }}"
    owner: "root"
    group: "root"
    mode: 0644
  when: cagui_enable_cronjob | bool
